src/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from notes.views import list_view, finished_item, delete_item, recover_item

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', list_view, name='home'),
    path('finished_item/<id>', finished_item, name='finished_item'),
    path('recover_item/<id>', recover_item, name='recover_item'),
    path('delete_item/<id>', delete_item, name='delete_item'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/notes/models.py
from django.db import models
from django.shortcuts import reverse

LABEL_CHOICE = (
    ('P', 'primary'),
    ('SE', 'secondary'),
    ('S', 'success'),
    ('DR', 'danger'),
    ('W', 'warning'),
    ('I', 'info'),
    ('L', 'light'),
    ('D', 'dark'),
)


class Note(models.Model):
    title = models.CharField(max_length=100)
    due_date = models.DateField()
    label = models.CharField(choices=LABEL_CHOICE, max_length=2)
    finished = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def get_finished_item_url(self):
        return reverse("finished_item", kwargs={
            'id': self.id
        })

    def get_recover_item_url(self):
        return reverse("recover_item", kwargs={
            'id': self.id
        })

    def get_delete_item_url(self):
        return reverse("delete_item", kwargs={
            'id': self.id
        })

src/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    def __str__(self):
        return self.username

src/notes/forms.py
from django import forms
from .models import Note


class NoteModelForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ('title', 'due_date', 'label')

src/notes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Note
from .forms import NoteModelForm


def list_view(request):
    form = NoteModelForm()
    if request.method == "POST":
        form = NoteModelForm(request.POST or None)
        if form.is_valid():
            form.save()
            return redirect('home')
    todo_list = Note.objects.filter(finished=False)
    finished_list = Note.objects.filter(finished=True)

    template = 'notes/list.html'
    context = {
        'todo': todo_list,
        'finished': finished_list,
        'form': form,
    }

    return render(request, template, context)


def finished_item(request, id):
    item = get_object_or_404(Note, id=id)
    item.finished = True
    item.save()

    return redirect('home')


def recover_item(request, id):
    item = get_object_or_404(Note, id=id)
    item.finished = False
    item.save()

    return redirect('home')


def delete_item(request, id):
    item = get_object_or_404(Note, id=id)
    item.delete()

    return redirect('home')

src/users/views.py
from django.shortcuts import render

# Create your views here.

src/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Lora:wght@400;500;700&family=Playfair+Display:wght@400;500;700;900&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.1/font/bootstrap-icons.css"
    />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <title>Django Notes | {% block title %}{% endblock title %}</title>
  </head>
  <body>
    <header id="header">
      {% block header %} {% include 'partials/nav.html' %} {% endblock header %}
    </header>

    <main id="main" class="container">
      {% block content %}{% endblock content %}
    </main>

    <footer class="contianer-fluid" id="footer">
      {% block footer %}{% endblock footer %}
    </footer>

    <!-- JavaScript Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

src/templates/notes/list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block content %}
<div class="row">
    <section class="col-lg-6 col-md-12">
        <div class="text-center mt-5">
            <h2>
                To-Do List
                <a class="btn btn-outline-primary" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                    <i class="bi bi-plus"></i>
                </a>
            </h2>
            <hr>
        </div>
            <div class="collapse m-2 border rounded px-3 py-2 border-secondary" id="collapseExample">
                <form method="post">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <input type="submit" value="Submit" class="btn btn-outline-primary">
                </form>
            </div>
        {% for note in todo %}
        <div class="card m-2 ">
            <div class="card-body d-flex justify-content-between align-items-baseline">
                <p>
                    {{note.title}} due on <span class="badge bg-{{note.get_label_display}}">{{ note.due_date}}</span>
                </p>
                <span class="action-icons">
                    <a href="{{ note.get_finished_item_url }}"  class="btn btn-outline-success">
                        <i class="bi bi-check"></i></i>
                    </a>
                    <a href="{{ note.get_delete_item_url }}" class="btn btn-outline-danger">
                        <i class="bi bi-trash"></i>
                    </a>
                </span>
            </div>
        </div>
        {% endfor %}
    </section>
    <section class="col-lg-6 col-md-12">
        <div class="text-center mt-5">
            <h2>Finished List</h2>
            <hr>
        </div>
        {% for note in finished %}
        <div class="card m-2">
            <div class="card-body d-flex justify-content-between align-items-baseline">
                <p>
                    {{note.title}} due on <span class="badge bg-{{note.get_label_display}}">{{ note.due_date}}</span>
                </p>
                <span class="action-icons">
                    <a href="{{ note.get_recover_item_url }}" class="btn btn-outline-primary">
                        <i class="bi bi-x"></i>
                    </a>
                    <a href="{{ note.get_delete_item_url }}" class="btn btn-outline-danger">
                        <i class="bi bi-trash"></i>
                    </a>
                </span>
            </div>
        </div>
        {% endfor %}
    </section>
</div>
{% endblock content %}

src/templates/partials/nav.html
<nav class="navbar navbar-dark bg-dark navbar-expand-lg">
  <div class="container">
    <a class="navbar-brand" href="#">Django NoteApp</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="#">Home</a>
        <a class="nav-link" href="#">Notes</a>
        <a class="nav-link" href="#">Categories</a>
      </div>
    </div>
  </div>
</nav>